### ISSUE TITLE
Hangup doesn't close the audio stream at least

### ISSUE THREAD

**Issue by LucMoreau33560** [flutter-webrtc/flutter-webrtc-demo#98]
Hello,

I run the demo on 2 devices (one iphone 7, one huawei P8Lite), it works good. Picture and audio are ok.
The problem is when I hang up, the audio (mic and speaker) still works and the stream is sent to the other deivce.
the code for demo is the last available on git. Same for the signaling server. No modificétionee

What can be the issue ?

**Comment by stefan1010** [comment]
Same problem here. I tried to find the problem, but so far I suspect it to be a problem not in the demo app, but the webrtc implementation.
Anyway there is what seems to be a bug in signaling.dart in the onMessage handler at the "bye"-case with closing the peer connection. data['to'] is used, whereas 'from' would be required. Since the server implementation doesn't include that in the data, without modifying the signaling-server, an option is to extract it from the sessionId, and then use it to reference the peer connection. anyway it didn't fix the audio issue for me.
